version: '3.8'

services:
  # Qdrant 向量数据库 - 使用本地缓存镜像
  qdrant:
    image: qdrant/qdrant:latest
    container_name: mem0-qdrant-simple
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data_simple:/qdrant/storage
    environment:
      - QDRANT_LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis缓存 - 使用本地缓存镜像
  redis:
    image: redis:7-alpine
    container_name: mem0-redis-simple
    ports:
      - "6379:6379"
    volumes:
      - redis_data_simple:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  qdrant_data_simple:
  redis_data_simple:

networks:
  default:
    name: mem0-simple-network